---
- hosts: raspberry
  become: yes
  vars:
      ANGULAR_DIST_DIR: /Users/robertopozzi/dev/windfire-profile/dist/windfire-profile
      WINDFIRE_HOME_DIR: /home/pi/windfire
      WINDFIRE_APP_FILES_DIR: windfire-profile
      APACHE2_DOC_DIR: /var/www/html
  tasks:
    - name: Transfer Angular Files
      copy:
        src: "{{ ANGULAR_DIST_DIR }}"
        dest: "{{ WINDFIRE_HOME_DIR }}"
    - name: Clean Apache2 folder {{ APACHE2_DOC_DIR }}
      file:
        path: "{{ APACHE2_DOC_DIR }}/"
        state: absent
    - name: Copy Angular application files from {{ WINDFIRE_HOME_DIR }}/{{ WINDFIRE_APP_FILES_DIR }} to Apache2 folder {{ APACHE2_DOC_DIR }}
      shell: 'cp -r {{ WINDFIRE_HOME_DIR }}/{{ WINDFIRE_APP_FILES_DIR }} {{ APACHE2_DOC_DIR }}'
    - name: Clean folder {{ WINDFIRE_HOME_DIR }}/{{ WINDFIRE_APP_FILES_DIR }}
      file:
        path: "{{ WINDFIRE_HOME_DIR }}/{{ WINDFIRE_APP_FILES_DIR }}/"
        state: absent